---
title: Capitol Cider House
timezone: America/New_York
collections:
  our-ciders:
    title: Ciders
    output: true
  events:
    title: Events
    output: true
  our-ports:
    title: Ports
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: events
  values:
    title: Spooky Trivia
    event-date: 2018-06-22 04:00:00.000000000 Z
    end-time: 2AM
    giphy-url: https://media.giphy.com/media/3ohs7KViF6rA4aan5u/giphy.gif
    event-url:
- scope:
    path: ''
    type: our-ciders
  values:
    title: Wild Gold
    tasting-notes: Dry, green apple, wild fermented
- scope:
    path: ''
    type: our-ports
  values:
    title: Goldrush
    tasting-notes: Sweet, honey, butterscotch
email: hello@capitolciderhouse.com
opening-date:
description: Capitol Cider House is cidery and taproom located at 3930 Georgia Avenue,
  steps from the metro in the heart of D.C.’s Petworth neighborhood. We focus on creating
  and curating craft hard cider with modern flavors.
url: https://capitolciderhouse.com
permalink: pretty
social-media-image: "/uploads/cch_OG.png"
is-resy: true
exclude:
- node_modules
- gulpfile.js
