---
title: Capitol Cider House
timezone: America/New_York
collections:
  cideries:
    title: Cideries
    output: true
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: cideries
  values:
    distance: 1.2 Miles
logo:
email: hello@capitolciderhouse.com
description: Capitol Cider House brewery and bar is located in D.C.’s Petworth neighborhood.
  We focus on traditional craft hard cider brewing with modern flavors, producing
  more than [#] hand pressed ciders.
url: https://capitolciderhouse.com
permalink: pretty
social-media-image:
opening-date: 2018-06-24 04:00:00.000000000 Z
exclude:
- node_modules
- gulpfile.js
opening-date: 2018-06-24 04:00:00.000000000 Z
