---
title: Capitol Cider House
timezone: America/New_York
collections:
  cideries:
    title: Cideries
    output: true
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: cideries
  values:
    distance: 1.2 Miles
email: hello@capitolciderhouse.com
opening-date: 2018-06-30 04:00:00.000000000 Z
description: Capitol Cider House is located at 3930 Georgia Avenue, steps from the metro in the heart of D.C.’s Petworth neighborhood. We focus on creating and curating craft hard cider with modern flavors.
url: https://capitolciderhouse.com
permalink: pretty
social-media-image: "/uploads/cch_OG.png"
exclude:
- node_modules
- gulpfile.js
